# numpy 

In [1]:
# how to create array
import numpy as np
arr=np.array([[1,2,3],
              [4,5,6]
    
])
print("Array\n",arr)

Array
 [[1 2 3]
 [4 5 6]]


In [2]:
import numpy as np
arr=np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
import numpy as np
arr=np.array([[10,20,30],
             [40,50,60],
             [70,80,90]])
print(arr)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [4]:
type(arr)

numpy.ndarray

In [5]:
arr.shape

(3, 3)

In [6]:
arr.size

9

In [7]:
arr.ndim

2

In [8]:
arr.ndim

2

In [9]:
import numpy as np
arr=np.array([[10,20,30,40],
             [40,50,60,50],
             [70,80,90,60],
             [100,120,130,70],
             [15,150,125,80]])
print(arr)
print(arr.shape)
print(arr.ndim)

[[ 10  20  30  40]
 [ 40  50  60  50]
 [ 70  80  90  60]
 [100 120 130  70]
 [ 15 150 125  80]]
(5, 4)
2


In [10]:
# this is one dimensional array 
import numpy as np 
a = np.arange(24) 
print(a)
a.ndim  

# now reshape it 
b = a.reshape(2,4,3)

print(b)
print(b.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]
3


In [11]:
# second example:-
import numpy as np
a=np.array([[1,2,3,],[4,5,6]],dtype='int')
b=np.array([1,3,5])  
c=np.zeros((3,4)) # row,column
d=np.full((3,3),4,dtype='int')
e=np.random.random((2,2))
f=np.linspace(0,5,9)
h=np.arange(0,30,2)
print(a)


[[1 2 3]
 [4 5 6]]


In [12]:
print(b)

[1 3 5]


In [13]:
print(c)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [14]:
print(d)

[[4 4 4]
 [4 4 4]
 [4 4 4]]


In [15]:
print(e)

[[0.41586046 0.0838525 ]
 [0.24326022 0.72127908]]


In [16]:
print(f)

[0.    0.625 1.25  1.875 2.5   3.125 3.75  4.375 5.   ]


In [17]:
print(h)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28]


In [18]:
arr=np.array([[1,2,3,8],
             [4,5,6,7],
             [7,8,9,5]])
print(arr)
print(arr.shape)
print("\n")
newarr=arr.reshape(2,3,2)
print(newarr)
print(newarr.shape)

[[1 2 3 8]
 [4 5 6 7]
 [7 8 9 5]]
(3, 4)


[[[1 2]
  [3 8]
  [4 5]]

 [[6 7]
  [7 8]
  [9 5]]]
(2, 3, 2)


In [19]:
arr=np.array([[1,2,3],[4,5,6]])
f=arr.flatten()
f

array([1, 2, 3, 4, 5, 6])

In [20]:
# numpy 1000 page
# pandas 2000 page
# matplotlib  500 page 

# Second part

# numpy

In [21]:
# indexing/ slicing in numpy
import numpy as np
arr=np.array([[1,2,3,4],
             [5,6,7,8],
             [9,10,11,12],
             [13,14,15,16]])
print(arr.shape)
# slicing array
temp=arr[:3,::3] # before coma work for row and after coma work for column
print("\n",temp)


temp=arr[1:3:1,1:2:2] # before coma work for row and after coma work for column
print("\n",temp)

(4, 4)

 [[ 1  4]
 [ 5  8]
 [ 9 12]]


In [ ]:
# indexing/ slicing in numpy
import numpy as np
arr=np.array([[1,2,3,4],
             [5,6,7,8],
             [9,10,11,12],
             [13,14,15,16]])
print(arr.shape)
# slicing array
temp=arr[1::3,::2] # before coma work for row and after coma work for column
print("\n",temp)


In [22]:
x="abcedfghijklmnop"
print(x[::1])
print(x[10:2:2])

abcedfghijklmnop



In [45]:
import numpy as np
arr1=np.array([[1,2,3,4],
            [5,6,7,8],
            [9,10,11,12],
            [13,14,15,16]])

print("\n")
temp=arr1[:2,::2]
print(temp)



[[1 3]
 [5 7]]


In [46]:
import numpy as np
arr=np.array([[1,2,3,4],
            [5,6,7,8],
            [9,10,11,12],
            [13,14,15,16]])

print("\n")
temp=arr[1::3,::2]
print(temp)



[[5 7]]


In [47]:
# integer array indexing
import numpy as np
arr=np.array([[1,2,3,4],
            [5,6,7,8],
            [9,10,11,12],
            [13,14,15,16]])

temp=arr[[0,1,2,3],[3,2,1,0]]# row,column
print("element at indices (0,3),(1,2),(2,1),(3,0)\n",temp)

[1,3,2,1],[2,1,2,0]

element at indices (0,3),(1,2),(2,1),(3,0)
 [ 4  7 10 13]


In [26]:
# boolean array indexing 
cond=arr>5 # cond is a boolean array
temp=arr[cond]
print("elements greater than 5\n",temp)

elements greater than 5
 [ 6  7  8  9 10 11 12 13 14 15 16]


In [27]:
# basic operations:-
a=np.array([1,2,3,4])
print("adding 1 value to every element",a+1)

adding 1 value to every element [2 3 4 5]


In [28]:
print("subtract 1 value to every element",a-1)

subtract 1 value to every element [0 1 2 3]


In [29]:
print("multiply 1 value to every element",a*1)

multiply 1 value to every element [1 2 3 4]


In [30]:
print("squaring 1 value to every element",a**2)

squaring 1 value to every element [ 1  4  9 16]


In [31]:
a*=2
print("doubled 1 value to every element",a)

doubled 1 value to every element [2 4 6 8]


In [32]:
# transpose
a=np.array([[1,2,3],[3,4,5],[9,6,0]])
print("original array\n",a)

original array
 [[1 2 3]
 [3 4 5]
 [9 6 0]]


In [33]:
print("transpose of array\n",a.T)

transpose of array
 [[1 3 9]
 [2 4 6]
 [3 5 0]]


In [34]:
# unary op
a=np.array([[1,2,3],
           [4,7,8],
           [3,1,9]])
print("largest elements ",a.max())

largest elements  9


In [35]:
print("row wise max elements",a.max(axis=1))# value check for every row

row wise max elements [3 8 9]


In [36]:
print("column wise minimum",a.min(axis=0))# value check for every column

column wise minimum [1 1 3]


In [37]:
print("sum of all array",a.sum())

sum of all array 38


In [38]:
print("cumulative sum along each row \n",a.cumsum(axis=1))


cumulative sum along each row 
 [[ 1  3  6]
 [ 4 11 19]
 [ 3  4 13]]


In [39]:
print("cumulative sum along each row \n",a.cumsum(axis=0))


cumulative sum along each row 
 [[ 1  2  3]
 [ 5  9 11]
 [ 8 10 20]]


In [40]:
print("end numpy for Machine learning.")

end numpy for Machine learning.
